### ISSUE TITLE
Grid - disable loading overlay

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#401]
The grid flashes a default `loadingOverlay` with the text "Loading..." in a div with a border. See https://www.ag-grid.com/javascript-grid-overlays/.

+ When exactly does it show? While the grid is busy internally processing and preparing to render data? Do we want this at all? Should we offer an option to disable?
+ If we decide to keep this, suggest we remove the default border via something like:
```css
.ag-theme-balham .ag-overlay-loading-center {
  border: none !important;
}
```
